# Generated by Django 5.0.6 on 2024-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='Оригинальный текст, который отображается на сайте.', max_length=20000, verbose_name='Оригинальный текст')),
                ('current_text', models.TextField(help_text='Измененный или текущий текст, который отображается на сайте.', max_length=20000, verbose_name='Текущий текст')),
            ],
            options={
                'verbose_name': 'Текст на сайте',
                'verbose_name_plural': 'Текста в сайте',
            },
        ),
    ]
